# Fernando Ulises Gomez Sanchez
# Programa que te pida el semestre en el que estás y que te imprima las materias y créditos de cada semestre

print ("Algoritmo Semestres")

s= int(input("En que semestre estas: 1, 2, 3, 4, 5, 6, 7, 8: "))
if s == 1 :
	print ("Semestre 1")
	print ("Calculo diferencial")
	print ("Fundamentos de Programacion")
	print ("Matematicas Discretas I")
	print ("Intoduccion a las TICs")
	print ("Taller de etica")
	print ("Findamentos de Investigacion")
	print ("Total de creditos = 26")
elif s == 2:
	print ("Semestre 2")
	print ("Calculo Integral")
	print ("Programacion Orientada a Objetos")
	print ("Matematicas Discretas II")
	print ("Probabilidad y Estadistica")
	print ("Contabilidad y Costos")
	print ("Total de creditos = 25")
elif s == 3:
	print ("Semestre 3")
	print ("Matematicas aplicadas a comunicaciones")
	print ("Estructura y organizacion de datos")
	print ("Administracion gerencial")
	print ("Fundamentos de bases de datos")
	print ("Electricidad y magnetismo")
	print ("Algebra lineal")
	print ("Total de creditos = 27")
elif s == 4:
	print ("Semestre 4")
	print ("Analisis de señales y sistemas")
	print ("Programacion II")
	print ("Matemáticas para la Toma de Decisiones")
	print ("Taller de Base de Datos")
	print ("Circuitos Eléctricos y Electrónicos")
	print ("Ingeniería de Software")
	print ("Total de creditos = 28")
elif s == 5:
	print ("Semestre 5")
	print ("Fundamentos de Redes")
	print ("Telecomunicaciones")
	print ("Administración de Proyectos")
	print ("Base de datos distribuidas")
	print ("Arquitectura de Computadoras")
	print ("Taller de Ingeniería de Software")
	print ("Total de creditos = 28")
elif s == 6:
	print ("Semestre 6")
	print ("Redes de Computadoras")
	print ("Programación Web ")
	print ("Desarrollo de emprendedores")
	print ("Taller de investigación I")
	print ("Sistemas Operativos I")
	print ("Tecnologías Inalámbricas")
	print ("Total de creditos = 28")
elif s == 7:
	print ("Semestre 7")
	print ("Redes Emergentes")
	print ("Desarrollo de Aplicaciones para Dispositivos Móviles")
	print ("Desarrollo Sustentable")
	print ("Taller de investigación II")
	print ("Sistemas Operativos II")
	print ("Negocios Electrónicos I")
	print ("Total de creditos = 28")
elif s == 8:
	print ("Semestre 8")
	print ("Administración y Seguridad de Redes")
	print ("Auditoría en Tecnologías de la Información")
	print ("Interacción Humano Computadora")
	print ("Ingeniería del conocimiento")
	print ("Negocios Electrónicos II")
	print ("Total de creditos = 21")
else:
	print("Error")

print("Fin")